### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by kalegd** [ashconnell/physx-js#4]
I'm not terribly familiar with npm so I'm not entirely sure if this is an issue on my end or not(sorry if it is), but I'm unable to run npm install after cloning the repo. This is the log that I get

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose npm-session af4b2e3d4e35ebdf
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall physx-js@0.0.9
7 info lifecycle physx-js@0.0.9~preinstall: physx-js@0.0.9
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 8ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly fetchPackageMetaData error for physx@github:prestomation/PhysX#emscripten_wip premature close
18 timing stage:rollbackFailedOptional Completed in 0ms
19 timing stage:runTopLevelLifecycles Completed in 18019ms
20 silly saveTree physx-js@0.0.9
21 verbose stack Error: premature close
21 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
21 verbose stack     at PassThrough.emit (events.js:187:15)
21 verbose stack     at emitCloseNT (internal/streams/destroy.js:59:8)
21 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
22 verbose cwd /Users/kalegd/Documents/workspace/xr_websites/experiments/physx/tmp/physx-js
23 verbose Darwin 18.7.0
24 verbose argv "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/bin/npm" "install"
25 verbose node v10.12.0
26 verbose npm  v6.4.1
27 error premature close
28 verbose exit [ 1, true ]
```

It looks like the error is in this line
`17 silly fetchPackageMetaData error for physx@github:prestomation/PhysX#emscripten_wip premature close`

But I have no idea why as that's a valid branch

(side note, thank you for putting up this up! I've really enjoyed integrating PhysX with three.js over the past month!)

**Comment by ashconnell** [comment]
Interesting. I get the same error with `npm` but it works fine with `yarn`. 

In `package.json` it adds the physx source github repo as a dependency (as opposed to an actual npm package) so it might be that yarn understands this format but npm does not.

I assume you are trying to add/edit some of the PhysX bindings? If so you can alternatively just clone the physx repo this repo tracks (prestomation/PhysX#emscripten_wip) and manually follow the scripts used in this repo to generate/make builds.

The current problem with this repo is that it can't receive PR's for new bindings etc because they need to happen in @prestomation's branch, and then this repo would be updated to pull from the latest and publish to npm. We also can't bundle all of these examples/scripts in that repo because it's not likely nvidia will want it there when it gets merged back in.

Any suggestions on how to better handle this would be great. Would love to see what you're working on!

**Comment by kalegd** [comment]
Ah I completely get the whole keeping that other repo clean for the sake of getting it merged with nvidia, so having everything setup the way it is works fine. And I'll try out yarn, and if I have no luck with that I'll go with prestomation's branch

I'm currently working on a Chess game with physics so people using VR headsets can play normally or scale themselves down to push pieces around in a life size game (and a non physics option so mobile and desktop users can play with VR users). The binding I'm considering adding is for setting maximum depenetration velocity for PxRigidBodys. Having a chess piece going from kinematic actor to not partially inside of the floor causes all sorts of problems/flying haha

**Comment by ashconnell** [comment]
That sounds amazing! It will be awesome to experience the scaling feature. 

I actually have depenetration bindings on my TODO list so if you want to share an updated bindings file i can make a build, update my PR on preston's branch and make a release to npm for you :D 

No worries if you can't, i'll get to it at some point in the future
